#!/bin/bash

# Netlify Deployment Script - Personal Profile Website
# This script provides instructions for deploying your website on Netlify

echo "Netlify Deployment Script - Personal Profile Website"
echo "===================================================="
echo ""
echo "Netlify is the BEST FREE option for your website because:"
echo "- Zero configuration required"
echo "- Automatic HTTPS"
echo "- Global CDN for fast loading"
echo "- Custom domain support"
echo "- Automatic deployments from Git"
echo "- Form handling"
echo "- Analytics and insights"
echo "- Free tier includes:"
echo "  * 100GB bandwidth/month"
echo "  * 300 build minutes/month"
echo "  * Unlimited personal projects"
echo ""

echo "QUICK DEPLOYMENT (Drag & Drop Method):"
echo "1. Go to https://netlify.com"
echo "2. Click 'Sign up' (use GitHub for easiest setup)"
echo "3. After signing in, you'll see the dashboard"
echo "4. DRAG AND DROP your entire website folder to the deployment area"
echo "5. Wait 10-30 seconds for upload and processing"
echo "6. Your site will be live with a random URL like:"
echo "   https://random-name-123456.netlify.app"
echo "7. Click 'Site settings' → 'Change site name' to customize URL"
echo ""

echo "CUSTOM DOMAIN SETUP:"
echo "- Go to 'Domain management' in your site settings"
echo "- Click 'Add custom domain'"
echo "- Enter your domain (e.g., adityarustagi.com)"
echo "- Follow the DNS configuration instructions"
echo "- Netlify will automatically provision SSL certificate"
echo ""

echo "TESTING YOUR WEBSITE:"
echo "- Test all pages and functionality"
echo "- Check responsive design on mobile devices"
echo "- Verify contact form works (if applicable)"
echo "- Test loading speed and performance"
echo "- Check browser compatibility"
echo ""

echo "ADVANCED SETUP (Git Integration for Easy Updates):"
echo ""
echo "1. Connect your GitHub repository:"
echo "   - In Netlify dashboard, click 'New site from Git'"
echo "   - Choose GitHub and authorize access"
echo "   - Select your repository"
echo "   - Set build settings:"
echo "     * Build command: (leave empty for static sites)"
echo "     * Publish directory: (leave empty for root directory)"
echo ""

echo "2. Automatic deployments:"
echo "   - Every push to main branch triggers automatic deployment"
echo "   - Preview deployments for pull requests"
echo "   - Rollback to previous versions if needed"
echo ""

echo "3. Environment variables (if needed):"
echo "   - Go to Site settings → Environment variables"
echo "   - Add any API keys or configuration values"
echo "   - These are automatically available during build"
echo ""

echo "4. Form handling:"
echo "   - Netlify automatically detects HTML forms"
echo "   - No backend code required"
echo "   - Spam protection included"
echo "   - Form submissions sent to your email"
echo ""

echo "5. Performance optimization:"
echo "   - Automatic image optimization"
echo "   - CSS and JS minification"
echo "   - Gzip compression"
echo "   - Browser caching"
echo ""

echo "Ready to deploy on Netlify!"
echo ""
echo "Your website will be live in minutes with professional hosting,"
echo "automatic HTTPS, and global CDN distribution." 